M48
; DRILL file {KiCad 7.0.9} date Wednesday, February 14, 2024 at 11:05:44 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-14T23:05:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1378
%
G90
G05
T1
X3.2862Y-3.1642
X3.2862Y-3.3917
T2
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T3
X3.7284Y-5.7394
T4
X3.1644Y-2.71
T5
X3.3372Y-3.7395
X4.9657Y-5.3681
T6
X3.335Y-5.3685
X4.963Y-3.7366
T0
M30
