M48
; DRILL file {KiCad 7.0.9} date Sunday, January 07, 2024 at 06:07:06 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-07T18:07:06-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1181
%
G90
G05
T1
X5.0174Y-3.5262
X5.0174Y-3.7538
T2
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T3
X3.7284Y-5.7394
T4
X3.2579Y-2.6516
T5
X3.435Y-2.6516
T6
X3.3372Y-3.7395
X4.9657Y-5.3681
T0
M30
