M48
; DRILL file {KiCad 7.0.2} date Thu Jan 11 01:28:20 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-11T01:28:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1181
%
G90
G05
T1
X5.0174Y-3.8567
X5.0174Y-4.0843
T2
X4.996Y-2.3735
X4.996Y-2.4535
X5.196Y-2.4135
T3
X3.7284Y-5.7394
T4
X3.2464Y-2.852
T5
X3.4235Y-2.852
T6
X3.3372Y-3.7395
X4.9657Y-5.3681
T0
M30
