M48
; DRILL file {KiCad 7.0.1} date Mon May 29 11:52:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-29T11:52:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T2
X3.7246Y-6.3557
T3
X3.1491Y-1.9922
X3.1504Y-6.36
X5.145Y-1.9923
X5.15Y-6.36
T0
M30
