M48
; DRILL file {KiCad (6.0.8-1)-1} date Tuesday, October 04, 2022 at 04:18:28 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-04T16:18:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X2.6114Y-4.0996
X2.6291Y-1.9311
X5.5878Y-4.0819
X5.5937Y-1.9579
T2
X2.6915Y-2.2017
X4.3201Y-3.8303
T0
M30
