M48
; DRILL file {KiCad 8.0.7} date 2025-01-03T15:46:10-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-03T15:46:10-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C0.1378
%
G90
G05
T1
X3.2862Y-3.1642
X3.2862Y-3.3917
T2
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T3
X3.7284Y-5.7394
T4
X3.2413Y-2.6228
T5
X3.4185Y-2.6228
T6
X3.3372Y-3.7395
X4.9657Y-5.3681
T7
X3.335Y-5.3685
X4.963Y-3.7366
M30
